name: self hosted runner

on: [push]

jobs:
  run-shell-command:
    runs-on: self-hosted
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: Try the cluster !
        run: kubectl get pods -A